### ISSUE TITLE
Missing docs for 0.8.0.1 on Hackage

### ISSUE THREAD

**Issue by expipiplus1** [kolmodin/binary#101]
Hackage seems to have stalled generating the documentation.

There's a neat script to generate an upload docs here: https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh

**Comment by kolmodin** [comment]
Hopefully we can poke the server to regenerate the docs. There is no reason why it shouldn't work.

**Comment by expipiplus1** [comment]
Hmm, they still seem to be missing.

**Comment by kolmodin** [comment]
@hvr uploaded new docs.
