### ISSUE TITLE
Data.Binary.Builder VS Data.Binary.Put

### ISSUE THREAD

**Issue by Daniel-Diaz** [kolmodin/binary#102]
Both modules have the same purpose: efficient construction of lazy bytestrings. When and why should one of them be picked over the other? Is it just a difference of style or are there any performance trade-offs to consider?

Thanks.

**Comment by kolmodin** [comment]
`Builder` is a `Monoid` which is all you really need when you want to construct bytestrings.
`Put` is implemented on top of `Builder` and provides a monadic interface. `Put` is also used in the `Binary` class for the `put` method.

In retrospect we see that there was no need for a `Put` monad. Just using `Builder` for everything would have worked just fine.

**Comment by Daniel-Diaz** [comment]
Thanks for your answer!
