### ISSUE TITLE
instance Binary Bool (get) throws exception on invalid inputs

### ISSUE THREAD

**Issue by iphydf** [kolmodin/binary#108]
In Data.Binary.Class:
```haskell
instance Binary Bool where
    put     = putWord8 . fromIntegral . fromEnum
    get     = liftM (toEnum . fromIntegral) getWord8
```

In GHC.Enum:
```haskell
instance Enum Bool where
  -- [...]
  toEnum n | n == 0    = False
           | n == 1    = True
           | otherwise = error "Prelude.Enum.Bool.toEnum: bad argument"
 ```

This makes Binary unusable for any data structure containing Bool. I don't want runGetIncremental to throw exceptions, I want it to return Fail. A workaround for this is to have a newtype around Bool and define a non-throwing Binary instance on it: https://github.com/TokTok/hstox/blob/master/src/Network/Tox/Encoding.hs#L15 (no guarantees for stability of this link).

**Comment by kolmodin** [comment]
Nice catch! Same is true for the `Ordering` instance a few lines down.
