### ISSUE TITLE
Binary instance for Complex?

### ISSUE THREAD

**Issue by sid-kap** [kolmodin/binary#109]
Would you accept a pull request with a Binary instance for Complex? 

It would be something like
```haskell
instance Binary a => Binary (Complex a)
  where
    put (r :+ i) = put (r, i)
    get = (\(r,i) -> r :+ i) <$> get
```

It would be nice to have an instance so that we can use it in http://github.com/albertoruiz/hmatrix. I think it might be a better idea to put the instance in the binary package rather than creating an orphan instance.

**Comment by kolmodin** [comment]
Yes, sure.
