### ISSUE TITLE
Get ByteString accepts negative size

### ISSUE THREAD

**Issue by iphydf** [kolmodin/binary#127]
For negative size (anything >2^63 on 64 bit systems), `get :: Get ByteString` returns the empty byte string. It should instead cause an error for strings that are too large to represent. On 32 bit systems, we have 31 bits of `Int`. In general in Haskell, we have up to 2^29-1 (see [Data.Int](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Int.html)). Binary should check that the size is within the positive range of `Int` and fail if it isn't.

**Comment by kolmodin** [comment]
Did you run into a problem due to the current behavior?
Most or all of `get` or `take` methods in Haskell will accept a negative input and just return the empty string.
See for example `take` in the Prelude, `take` in attoparsec, `count` in parsec.
