### ISSUE TITLE
Put is missing runPutOrFail

### ISSUE THREAD

**Issue by okeuday** [kolmodin/binary#133]
It would help if it was added, to be similar to Get.

**Comment by kolmodin** [comment]
`runPut` cannot fail, so I'm not sure what `runPutOrFail` would do. @okeuday, can you clarify?
Executing `Get` can fail, thus we have `runGetOrFail`.

**Comment by okeuday** [comment]
@kolmodin I can understand that your main focus is where the binary package can fail, however, consider that other usage of the package also wants to return a failure.  The easiest solution is to throw an exception, but this causes problems for other source code that wants to remain pure, since these exceptions can only be caught within the source code closest to main that is impure.  The `Get` monad allows you to use `fail` to provide strings to `runGetOrFail` which is very convenient when doing validation on the decoded binary values.  The `Put` monad currently lacks a `runPutOrFail`, so that forces the developer to wrap `Put` with a monad transform to allow a String error to be returned (e.g., when checking an Int is in a 32bit or 16bit range before it is encoded).  So, it should be helpful to provide the additional function `runPutOrFail` despite the fact the failure will not be caused by the binary package.

**Comment by kolmodin** [comment]
Unfortunately, by that logic, any function in haskell that takes an argument needs to have a `fooOrFail` version. I think this is better handled at another layer, not making `binary` more complex.

You could have something like
```haskell
myPutter :: MyType -> Either String Put
```

Not representing errors in `Put` allows it to be faster. Put is nowadays implemented by Builders in ByteString.

See [`toLazyByteString`](https://hackage.haskell.org/package/bytestring-0.10.8.1/docs/Data-ByteString-Builder.html#v:toLazyByteString)  in ByteString, it does not return an error.
