### ISSUE TITLE
Performance question about ByteString append allocations

### ISSUE THREAD

**Issue by nh2** [kolmodin/binary#136]
Hi,

I'm investigating a performance problem.

I noticed that [`prompt`](https://github.com/kolmodin/binary/blob/4042fb5243872a4f75fd6fe1a6f6941708993660/src/Data/Binary/Get/Internal.hs#L173) and [`pushFront`](https://github.com/kolmodin/binary/blob/4042fb5243872a4f75fd6fe1a6f6941708993660/src/Data/Binary/Get/Internal.hs#L300) in `Data.Binary.Get.Internal` do `ByteString.append`s:

```haskell
prompt :: B.ByteString -> Decoder a -> (B.ByteString -> Decoder a) -> Decoder a
prompt inp kf ks = prompt' kf (\inp' -> ks (inp `B.append` inp'))
```

```haskell
pushFront :: B.ByteString -> Get ()
pushFront bs = C $ \ inp ks -> ks (B.append bs inp) ()
```

My first question is: Is this technically necessary?

I imagine that it should be possible to do `Get` parsing in a zero-copy fashion, simply continuing with the next `ByteString` in some list to work along, instead of actually O(n) appending what's pushed in front here.

My second question is: Given that these are internal functions, do you know if there any bounds on how much appending can be going on in the worst case? My first guess is roughly "at max 2x as much copying than there are bytes in the input", but I'd like to know if that's true.

**Comment by nh2** [comment]
(Note that the effect of this would probably be reduced by https://github.com/haskell/bytestring/pull/125 but nevertheless the two questions still stand.)

**Comment by kolmodin** [comment]
No, it's not technically necessary. `attoparsec` gives up on purity and achieves better performance. There should be better solutions also while keeping purity.

`pushFront` is only used in `isolate`. A far simpler implementation than the current `isolate` would be to demand all the required bytes at the start. Then there's no need to put any data back.

`pushBack` is used when backtracking in `<|>`. The way it's currently done its `O(n^2)` if you have small chunk sizes. If you don't control the chunk sizes yourself, for example, you read one byte at a time from a network socket, it would be bad. If the first branch prompts for some more input and then fails, that extra input is preserved by appending it to the previous chunk it needs to try the second branch.
This behavior is better than attoparsec used to have, but not as good as what it currently does.
The whole `Alternative` implementation is bolted on and not done as efficient as it could be. Good news is that you don't pay for any of it unless you use it.

**Comment by nh2** [comment]
Thanks for the explanation!
