### ISSUE TITLE
reinterpret-cast can now be faster

### ISSUE THREAD

**Issue by nh2** [kolmodin/binary#137]
@Daniel-Diaz @kolmodin Hi, I just found #119; I wrote the `reinterpret-cast` package from which you've taken the #119 implementation and wanted to make you aware of the fact that [GHC issue 4092](https://ghc.haskell.org/trac/ghc/ticket/4092) is now fixed, which means that GHC now offers a way to do a  reinterpret-cast without overhead.

You may be interested in looking into that to make Float/Double serialisation faster.

**Comment by Daniel-Diaz** [comment]
It also says "Unfortunately too late for the ghc-8.2 release, but it will make the ghc-8.4 release". This means we should wait, right?

**Comment by nh2** [comment]
@Daniel-Diaz yes, but since the commit is already there, it can at least be determined what exactly has to be done.
