### ISSUE TITLE
Why is the fixed size small value for Natural wider than that for Integer

### ISSUE THREAD

**Issue by expipiplus1** [kolmodin/binary#139]
`Natural` uses `Word64` and `Integer` uses `Word32`

https://github.com/kolmodin/binary/blob/master/src/Data/Binary/Class.hs#L365
https://github.com/kolmodin/binary/blob/master/src/Data/Binary/Class.hs#L304

CC @kolmodin

**Comment by kolmodin** [comment]
No real reason, that I can think of. Unfortunately it's too late to change since it'd mean that the wire format would change. The format is generally poorly designed.
