### ISSUE TITLE
How to change default byteorder?

### ISSUE THREAD

**Issue by ablearthy** [kolmodin/binary#183]
Int32 has [implementation](https://hackage.haskell.org/package/binary-0.10.0.0/docs/src/Data.Binary.Class.html#line-264) of `Binary` class, and `get` function is just `getInt32be`. 
The problem is that I should parse file format where little-endian order is used. Thus, I can't use generics and I should write lots of code (I did it, but I want to make the code beautiful)

**Comment by Daniel-Diaz** [comment]
@ablearthy One idea could be to use `newtype`. For example:

```haskell

newtype LEInt32 = LEInt32 Int32

instance Binary LEInt32 where
  put = putInt32le
  get = getInt32le
```

Now you can use `LEInt32` for little-endian and `Int32` for big-endian.

I hope that helps.

**Comment by ablearthy** [comment]
```haskell
newtype LE a = LE a

instance Binary (LE Word16) where
  get = do LE <$> getWord16le
  put (LE val)= putWord16le val 


instance Binary (LE Word32) where
  get = do LE <$> getWord32le
  put (LE val)= putWord32le val 

instance Binary (LE Word64) where
  get = do LE <$> getWord64le
  put (LE val)= putWord64le val 
```

Is this OK?

**Comment by Daniel-Diaz** [comment]
Those are illegal instances, although you can use `FlexibleInstances` to make them valid. However, I'd rather do:

```haskell
-- | Type to use little-endian serialization.
newtype LE a = LE a

-- | Little-endian serialization.
class LEBinary a where
  getLE :: Get a
  putLE :: a -> Put

-- | Binary instance for LE.
intance LEBinary a => Binary (LE a) where
  get = LE <$> getLE
  put (LE x) = putLE x
```

Once you have this you can add instances for the word types or anything else you want to make work with `LE`:

```haskell
instance LEBinary Word16 where
  getLE = getWord16le
  putLE = putWord16le

instance LEBinary Word32  where
  getLE = getWord32le
  putLE = putWord32le
```

And so on...

I haven't tried to compile the code, so maybe there's some type or error or something, but I hope the idea is clear.

@ablearthy

**Comment by ablearthy** [comment]
Oh, it looks really nice! Could it be implemented in the library or is it bad idea? The instances of `Binary` for `WordN`, `IntN`, etc. frustrates me. I can't choose between little-endian and big-endian. 

@Daniel-Diaz
