### ISSUE TITLE
`Data.Binary.Put` lacks `Put`s for `Int` types

### ISSUE THREAD

**Issue by bgamari** [kolmodin/binary#33]
`Data.Binary.Put` and `Data.Binary.Builder` provide a variety of `Put`s for various width `Word` types. I don't see any reason why they shouldn't include similar functionality for the signed types from `Data.Int`.

**Comment by Daniel-Diaz** [comment]
I think this issue can be closed now. See https://github.com/kolmodin/binary/pull/47.
