### ISSUE TITLE
Explain why the applicative style should be preferred over the monadic style

### ISSUE THREAD

**Issue by kolmodin** [kolmodin/binary#40]
Writing decoders in applicative style gives more efficient code, since boundary checks (check whether we have enough remaining input) can be merged.

Update the documentation to reflect this, README.md and haddock.

**Comment by expipiplus1** [comment]
This will probably be less important when ApplicativeDo hits.

**Comment by kolmodin** [comment]
This for getting my attention to this.
Applicative style is no longer more efficient than monadic style. Unfortunately it was very hard to achieve better performance with applicative since you had to get a lot of inlining to work, so hard that I decided to remove it. It was removed in `0.8.0.0` with 11816f1fb2400171d018b784b9522604819b8778.
