### ISSUE TITLE
Remove Binary instance for ByteString

### ISSUE THREAD

**Issue by joecrayne** [kolmodin/binary#68]
I find myself making the same error over and over again.  I use <code>get</code>when I mean <code>getByteString</code> or I use <code>put</code> when I mean <code>putByteString</code>.  It's occured to me that the Binary instance for ByteString is actually a very bad idea.  Instead, I suggest wrapping ByteString with a newtype that will define the current instance.  Although this may break some code, it would likely save more time than it costs over all for the library's end users.

**Comment by kolmodin** [comment]
`getByteString` takes an argument of how many bytes you need, so it shouldn't be so easy to confuse with `get` which doesn't take any arguments.
