### ISSUE TITLE
Risk of stack-overflow in roll

### ISSUE THREAD

**Issue by basvandijk** [kolmodin/binary#85]
I was just reading through the Binary instance of Integer and stumbled on the [roll]( https://github.com/kolmodin/binary/blob/master/src/Data/Binary/Class.hs#L251) function:

```haskell
roll :: (Integral a, Num a, Bits a) => [Word8] -> a
roll   = foldr unstep 0
  where
    unstep b a = a `shiftL` 8 .|. fromIntegral b
```

There's a risk of a stack-overflow here since it's lazily building the result value. Although the list of bytes will usually not be that big I think it would be better to build the value strictly using something like the following (untested):

```haskell
roll :: (Integral a, Num a, Bits a) => [Word8] -> a
roll = foldl' unstep 0
  where
    unstep a b = a `shiftL` 8 .|. fromIntegral b
```

**Comment by kolmodin** [comment]
Your fix might also be a tiny bit faster. We should extend our benchmark suite and then do this change.

**Comment by basvandijk** [comment]
Although my version is actually incorrect. I will add a correct version and write some benchmarks to see if it's more efficient than the foldr alternative.

**Comment by basvandijk** [comment]
Closing this in favour of #86.
